name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.SSH_HOST }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem

          # Sync project to EC2
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ ec2-user@$HOST:/home/ec2-user/nodeapp/

          # SSH and start/restart app
          ssh -i key.pem ec2-user@$HOST << 'EOF'
            cd ~/nodeapp
            npm install
            pm2 stop ecommerce || true
            pm2 start app.js --name ecommerce
            pm2 save
          EOF
